name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: Release ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: compile
      run: yarn compile
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn release