name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: Release ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: yarn install
    - name: compile
      run: yarn compile
    - name: build
      run: yarn build
    - name: publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn publish